WITH all_mappings AS (
                         SELECT source_code,
                                source_concept_id,
                                source_vocabulary_id,
                                source_domain_id,
                                source_concept_class_id,
                                source_description,
                                source_description_synonym,
                                valid_start_date,
                                NULL AS relationship_id,
                                NULL AS predicate_id,
                                NULL AS confidence,
                                NULL AS target_concept_id,
                                NULL AS target_concept_code,
                                NULL AS target_concept_name,
                                NULL AS target_vocabulary_id,
                                NULL AS target_domain_id,
                                decision,
                                review_date,
                                reviewer_name,
                                reviewer_specialty,
                                reviewer_comment,
                                orcid_id,
                                reviewer_affiliation_name,
                                status,
                                author_comment,
                                change_required
                         FROM temp.gis_source
                         UNION ALL
                         SELECT source_code,
                                source_concept_id,
                                source_vocabulary_id,
                                target_domain_id AS source_domain_id,
                                'Suppl Concept'  AS source_concept_class_id,
                                source_description,
                                NULL             AS source_description_synonym,
                                now()::date valid_start_date, relationship_id,
                                predicate_id,
                                confidence,
                                target_concept_id,
                                NULL             AS target_concept_code,
                                target_concept_name,
                                target_vocabulary_id,
                                target_domain_id,
                                decision,
                                review_date,
                                reviewer_name,
                                reviewer_specialty,
                                reviewer_comment,
                                orcid_id,
                                reviewer_affiliation_name,
                                status,
                                author_comment,
                                change_required
                         FROM temp.gis_mapping
                         -- To add once first IDs are assigned
--                          UNION ALL
--                          SELECT source_code,
--                                 source_concept_id,
--                                 source_vocabulary_id,
--                                 target_domain_id AS source_domain_id,
--                                 'Suppl Concept' AS source_concept_class_id,
--                                 source_description,
--                                 NULL AS source_description_synonym,
--                                 now()::date valid_start_date,
--                                 relationship_id,
--                                 predicate_id,
--                                 confidence,
--                                 target_concept_id,
--                                 target_concept_code,
--                                 target_concept_name,
--                                 target_vocabulary_id,
--                                 target_domain_id,
--                                 decision,
--                                 review_date,
--                                 reviewer_name,
--                                 reviewer_specialty,
--                                 reviewer_comment,
--                                 orcid_id,
--                                 reviewer_affiliation_name,
--                                 status,
--                                 author_comment,
--                                 change_required
--                          FROM temp.gis_hierarchy

                     )

INSERT
INTO temp.source_to_update   (
                                source_code,
                                source_concept_id,
                                source_vocabulary_id,
                                source_domain_id,
                                source_concept_class_id,
                                source_description,
                                source_description_synonym,
                                valid_start_date,
                                relationship_id,
                                predicate_id,
                                confidence,
                                target_concept_id,
                                target_concept_code,
                                target_concept_name,
                                target_vocabulary_id,
                                target_domain_id,
                                decision,
                                review_date,
                                reviewer_name,
                                reviewer_specialty,
                                reviewer_comment,
                                orcid_id,
                                reviewer_affiliation_name,
                                status,
                                author_comment,
                                change_required)
SELECT TRIM(LEFT(source_code, 50)),
        NULL AS source_concept_id,
        source_vocabulary_id,
        source_domain_id,
        source_concept_class_id,
        LEFT(source_description, 255),
        LEFT(source_description_synonym, 255),
        valid_start_date,
        relationship_id,
        predicate_id,
        confidence::FLOAT,
        target_concept_id::integer,
        target_concept_code,
        target_concept_name,
        target_vocabulary_id,
        INITCAP(target_domain_id),
        decision,
        review_date,
        reviewer_name,
        reviewer_specialty,
        reviewer_comment,
        orcid_id,
        reviewer_affiliation_name,
        status,
        author_comment,
        change_required
FROM all_mappings
WHERE NULLIF (TRIM (LEFT (source_concept_code, 50)), '') IS NOT NULL
  AND TRIM (decision) = '1';

SELECT COUNT(*)
FROM temp.source_to_update;
