name: GIS Vocab Build
on:
  schedule:
    - cron: '15 12 * * 1-5'
  push:
    branches:
      - main
    paths:
      - 'GIS/Builder/**'
      - '.github/build-gis-vocab.yml'
    
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Generate a token
      id: generate-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ vars.APP_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}
    - uses: actions/checkout@v2
    - name: build vocabulary
      env:
        APP_TOKEN: ${{ steps.generate-token.outputs.token }}
      run: |
        echo "Launching vocab builder..." && \
          apt-get update && \
          apt-get install --no-install-recommends --yes postgresql-client && \
          chmod +x /tmp/runner/CVB/CVB/Builder/execute-pipeline.sh && \
          /tmp/runner/CVB/CVB/Builder/execute-pipeline.sh $PG_PASSWORD $PG_HOST
          rm -rf /tmp/runner/chorus-mapping-stage/chorus-mapping-stage/Ontology && mkdir /tmp/runner/chorus-mapping-stage/chorus-mapping-stage/Ontology
          cp /tmp/output/* /tmp/runner/chorus-mapping-stage/chorus-mapping-stage/Ontology/
          git config --global user.name 'omop-vocab-builder[bot]'
          git config --global user.email '183100713+omop-vocab-builder[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:$APP_TOKEN@github.com/$GITHUB_REPOSITORY
          git checkout main
          git add /tmp/runner/CVB/CVB/Ontology/*
          git commit -am "Converted Vocabulary Delta Files: `date +\"%Y-%m-%d\"`"
          git push
          
